name: "RCNN Predictor"
description: "Given the KeypointRCNNImageBackbone, predict the detections and save the results for later usage."

device: "cuda:0"
print_prio: "INFO"
is_training: off
log_dir: "./results/helpers/rcnn_predictor/"
log_dir_add_date: false

# #### #
# DATA #
# #### #

RCNN_Backbone:
    module_name: "KeypointRCNNImageBackbone"
    dataset_path: "./data/"
    base_path: "./data/PoseTrack21/images/val/"
    batch_size: 16
    # threshold:  # set by script
    return_lists: true
    image_size: !!python/tuple [ 1024, 1024 ]  # [H,W]
    image_mode: "zero-pad"
    crop_size: !!python/tuple [256, 192]  # [H,W]
    crop_mode: "zero-pad"
    # data_path:  # will be set in python script

submission:
    module_name: "PoseTrack21"
    # file:  # will be set in python script