name: "RCNN Predictor"
description: "Given the KeypointRCNNImageBackbone, predict the detections and save the results for later usage."

device: "cuda:0"
print_prio: "INFO"
is_training: off
log_dir: "./results/own/rcnn_predictor_log/"
log_dir_add_date: false

# ################ #
# SUBMISSION FILES #
# ################ #

submission_pt21:
    module_name: "PoseTrack21"
    # file:  # will be set in python script

submission_MOT:
    module_name: "MOT"
    # file:  # will be set in python script
    # seqinfo_key:  # will be set in python script


# #### #
# PT21 #
# #### #

RCNN_PT21_256x128_val:
    module_name: "KeypointRCNNImageBackbone"
    # data_path:  # will be set in python script
    dataset_path: "./data/PoseTrack21/"
    dataset_paths: "./data/PoseTrack21/images/val/**/"

    batch_size: 1
    collate_fn: "lists"

    # score_threshold:  # set by script
    # iou_threshold:  # set by script
    # mask_path:  # set by script
    bbox_min_size: 50.0

    crop_size: !!python/tuple [256, 128]  # [H,W]
    crop_mode: "zero-pad"

PT21_256x128_val:
    module_name: "PoseTrack21_Image"
    # data_path:  # will be set in python script
    dataset_path: "./data/PoseTrack21/"
    dataset_paths: "./data/PoseTrack21/posetrack_data/val/**.json"
    crops_folder: "./data/PoseTrack21/crops/256x128/val/"

    batch_size: 1
    collate_fn: "lists"

    crop_size: !!python/tuple [256, 128]  # [H,W]
    crop_mode: "zero-pad"
    load_img_crops: false

RCNN_PT21_256x192_val:
    module_name: "KeypointRCNNImageBackbone"
    # data_path:  # will be set in python script
    dataset_path: "./data/PoseTrack21/"
    dataset_paths: "./data/PoseTrack21/images/val/**/"

    batch_size: 1
    collate_fn: "lists"

    # score_threshold:  # set by script
    # iou_threshold:  # set by script
    # mask_path:  # set by script
    bbox_min_size: 50.0

    crop_size: !!python/tuple [256, 192]  # [H,W]
    crop_mode: "zero-pad"

RCNN_PT21_256x192_train:
    module_name: "KeypointRCNNImageBackbone"
    # data_path:  # will be set in python script
    dataset_path: "./data/PoseTrack21/"
    dataset_paths: "./data/PoseTrack21/images/train/**/"

    batch_size: 1
    collate_fn: "lists"

    # score_threshold:  # set by script
    # iou_threshold:  # set by script
    # mask_path:  # set by script
    bbox_min_size: 50.0

    crop_size: !!python/tuple [256, 192]  # [H,W]
    crop_mode: "zero-pad"

PT21_256x192_val:
    module_name: "PoseTrack21_Image"
    # data_path:  # will be set in python script
    dataset_path: "./data/PoseTrack21/"
    dataset_paths: "./data/PoseTrack21/posetrack_data/val/**.json"
    crops_folder: "./data/PoseTrack21/crops/256x192/val/"
    
    batch_size: 1
    collate_fn: "lists"

    crop_size: !!python/tuple [256, 192]  # [H,W]
    crop_mode: "zero-pad"
    load_img_crops: false

# ##### #
# MOT20 #
# ##### #

RCNN_MOT_256x192_train:
    module_name: "KeypointRCNNImageBackbone"
    # data_path:  # will be set in python script
    dataset_path: "./data/MOT20/"
    dataset_paths: "./data/MOT20/train/**/"

    batch_size: 1
    collate_fn: "lists"

    # score_threshold:  # set by script
    # iou_threshold:  # set by script
    bbox_min_size: 50.0

    crop_size: !!python/tuple [256, 192]  # [H,W]
    crop_mode: "zero-pad"

RCNN_MOT_256x192_test:
    module_name: "KeypointRCNNImageBackbone"
    # data_path:  # will be set in python script
    dataset_path: "./data/MOT20/"
    dataset_paths: "./data/MOT20/test/**/"

    batch_size: 1
    collate_fn: "lists"

    # score_threshold:  # set by script
    # iou_threshold:  # set by script
    bbox_min_size: 50.0

    crop_size: !!python/tuple [256, 192]  # [H,W]
    crop_mode: "zero-pad"

MOT_256x192_train:
    module_name: "MOTImage"
    # data_path:  # will be set in python script
    dataset_path: "./data/MOT20/"
    dataset_paths: "./data/MOT20/train/**/"

    batch_size: 1
    collate_fn: "lists"

    crop_size: !!python/tuple [256, 192]  # [H,W]
    crop_mode: "zero-pad"

# ########## #
# DanceTrack #
# ########## #

RCNN_Dance_256x192_train:
    module_name: "KeypointRCNNImageBackbone"
    # data_path:  # will be set in python script
    dataset_path: "./data/DanceTrack/"
    dataset_paths: "./data/DanceTrack/train/dancetrack*/"

    batch_size: 8
    collate_fn: "lists"

    # score_threshold:  # set by script
    # iou_threshold:  # set by script
    bbox_min_size: 50.0

    crop_size: !!python/tuple [256, 192]  # [H,W]
    crop_mode: "zero-pad"

RCNN_Dance_256x192_test:
    module_name: "KeypointRCNNImageBackbone"
    # data_path:  # will be set in python script
    dataset_path: "./data/DanceTrack/"
    dataset_paths: "./data/DanceTrack/test/dancetrack*/"

    batch_size: 1
    collate_fn: "lists"

    # score_threshold:  # set by script
    # iou_threshold:  # set by script
    bbox_min_size: 50.0

    crop_size: !!python/tuple [256, 192]  # [H,W]
    crop_mode: "zero-pad"

RCNN_Dance_256x192_val:
    module_name: "KeypointRCNNImageBackbone"
    # data_path:  # will be set in python script
    dataset_path: "./data/DanceTrack/"
    dataset_paths: "./data/DanceTrack/val/dancetrack*/"

    batch_size: 1
    collate_fn: "lists"

    # score_threshold:  # set by script
    # iou_threshold:  # set by script
    bbox_min_size: 50.0

    crop_size: !!python/tuple [256, 192]  # [H,W]
    crop_mode: "zero-pad"

Dance_256x192_train:
    module_name: "MOTImage"
    # data_path:  # will be set in python script
    dataset_path: "./data/DanceTrack/"
    dataset_paths: "./data/DanceTrack/train/dancetrack*/"

    batch_size: 32
    collate_fn: "lists"

    crop_size: !!python/tuple [ 256, 192 ]  # [H,W]
    crop_mode: "zero-pad"

Dance_256x192_val:
    module_name: "MOTImage"
    # data_path:  # will be set in python script
    dataset_path: "./data/DanceTrack/"
    dataset_paths: "./data/DanceTrack/val/dancetrack*/"

    batch_size: 32
    collate_fn: "lists"

    crop_size: !!python/tuple [ 256, 192 ]  # [H,W]
    crop_mode: "zero-pad"
