# ###### #
# TRACKS #
# ###### #
track:
    N: 5

tracks:
    inactivity_threshold: 30


# ###################### #
# Dataset and DataLoader #
# ###################### #
dataloader:
    batch_size: 16
    drop_last: False
    shuffle: False
    workers: 0

video_dataset:
    stream: "video"
    num_threads: 0
    video_backend: "pyav"

images:
    image_size: !!python/tuple [1024, 1024]
    image_mode: "zero-pad"
    crop_size: !!python/tuple [256, 256]
    crop_mode: "zero-pad"

# ############## #
# LOSS FUNCTIONS #
# ############## #

cross_entropy_loss:
    label_smoothing: 0.1


# ####### #
# MODULES #
# ####### #

engine:
    dgs:
        save_images: true
        show_keypoints: true
        show_skeleton: true


backbone:
    kprcnn:
        threshold: 0.3

similarity:
    torchreid:
        softmax: false

    oks:
        softmax: false

    iou:
        softmax: false

dgs:
    similarity_softmax: true
    combined_softmax: true