# ###### #
# TRACKS #
# ###### #

track:
    N: 5

tracks:
    inactivity_threshold: 30

# ###################### #
# Dataset and DataLoader #
# ###################### #

dataset:
    crops_folder: ""
    force_img_reshape: false

    pt21:
        check_img_sizes: false

    kprcnn:
        threshold: 0.3


dataloader:
    batch_size: 16
    drop_last: false
    shuffle: false
    workers: 0  # right now there is no full multi device support
    return_lists: false

video_dataset:
    stream: "video"
    num_threads: 0
    video_backend: "pyav"

images:
    image_size: !!python/tuple [1024, 1024]
    image_mode: "zero-pad"
    crop_size: !!python/tuple [256, 256]
    crop_mode: "zero-pad"
    jpeg_quality: 90
    aspect_mode: "zero-pad"
    aspect_round_decimals: 2

submission:
    file: "./submission.json"

# ############## #
# LOSS FUNCTIONS #
# ############## #

cross_entropy_loss:
    label_smoothing: 0.1

# ####### #
# MODULES #
# ####### #

base:
    print_prio: "INFO"
    description: ""
    log_dir: "./results/"
    log_dir_add_date: true
    precision: "float32"


engine:
    test:
        writer_kwargs: {}
        normalize: false

    train:
        epochs: 1
        start_epoch: 1
        save_interval: 5
        loss_kwargs: {}
        optim_kwargs:
            lr: 0.0001  # 1e-4
        scheduler: "StepLR"
        scheduler_kwargs:
            step_size: 1
            gamma": 0.1

    visual:
        topk_acc: [1]
        topk_cmc: [ 1, 5, 10, 20 ]
        metric_kwargs: {}
        write_embeds: [False, False]
        image_key: "image_crop"

    dgs:
        save_images: true
        show_keypoints: true
        show_skeleton: true
        draw_kwargs: {}

similarity:
    torchreid:
        softmax: false
        sim_kwargs: {}

    oks:
        softmax: false

    iou:
        softmax: false

dgs:
    similarity_softmax: true
    combined_softmax: true

embed_gen:
    embedding_key: "embedding"
    
    torchreid:
        weights: "pretrained"
        image_key: "image_crop"

    pose:
        LPBEG:
            bbox_format: "XYWH"
            bias: true
            hidden_layers: []

        KPCPBEG:
            bbox_format: "XYWH"
            bias: true
            nof_kernels: 5
            hidden_layers: []
            hidden_layers_kp: []