# ###### #
# TRACKS #
# ###### #

track:
    N: 5

tracks:
    inactivity_threshold: 30

# ###################### #
# Dataset and DataLoader #
# ###################### #

dataset:
    crops_folder: ""
    force_img_reshape: false

    kprcnn:
        threshold: 0.3


dataloader:
    batch_size: 16
    drop_last: false
    shuffle: false
    workers: 0  # right now there is no full multi device support
    return_lists: false

video_dataset:
    stream: "video"
    num_threads: 0
    video_backend: "pyav"

images:
    image_size: !!python/tuple [1024, 1024]
    image_mode: "zero-pad"
    crop_size: !!python/tuple [256, 256]
    crop_mode: "zero-pad"

# ############## #
# LOSS FUNCTIONS #
# ############## #

cross_entropy_loss:
    label_smoothing: 0.1

# ####### #
# MODULES #
# ####### #

base:
    print_prio: "INFO"
    description: ""
    log_dir: "./results/"
    precision: "float32"


engine:
    dgs:
        save_images: true
        show_keypoints: true
        show_skeleton: true

similarity:
    torchreid:
        softmax: false

    oks:
        softmax: false

    iou:
        softmax: false

dgs:
    similarity_softmax: true
    combined_softmax: true
