name: "Evaluate-IoU"
description: "Use the DGS tracker with a constant alpha module. 
With IoU as its only Similarity with an alpha value of 1."

device: "cuda"
print_prio: "INFO"
is_training: off
log_dir: "./results/own/eval/"

test:
    inactivity_threshold: 15
    max_track_length: 1
    save_images: off

# #### #
# DATA #
# #### #

dl_rcnn:
    module_name: "KeypointRCNNImageBackbone"
    dataset_path: "./data/"
    base_path: "./data/PoseTrack21/images/val/"
    batch_size: 16
    threshold: 0.75
    return_lists: true
    crop_size: !!python/tuple [256, 192]
    crop_mode: "zero-pad"
    # data_path:  # will be set in python script
    # out_path:  # will be set in python script

dl_gt:
    module_name: "PoseTrack21_Image"
    dataset_path: "./data/PoseTrack21/"
    crops_folder: "./data/PoseTrack21/crops/256x192/val/"
    base_path: "./data/PoseTrack21/posetrack_data/val/"
    batch_size: 1
    return_lists: true
    # data_path: # will be set in python script
    # out_path:  # will be set in python script

# ####### #
# MODULES #
# ####### #

combine_sim:
    module_name: "constant_alpha"
    alpha: [1.0]

# BOX - IoU

dgs_box:
    module_name: "DGS"
    combine: "combine_sim"
    names: ["box_sim"]
    combined_softmax: true

box_sim:
    module_name: "iou"

# Pose - OKS

dgs_pose:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "pose_sim" ]
    combined_softmax: true

pose_sim:
    module_name: "oks"
    format: "coco"


# Visual - v1 - OSNet_x1_0 pretrained on ImageNet

dgs_vis_1:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v1_sim" ]
    combined_softmax: true

v1_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v1_embed_gen"]

v1_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_x1_0"
    weights: "./weights/osnet_x1_0_imagenet.pth"
    nof_classes: 1000


# Visual - v2 - OSNet_ain_x1_0 pretrained on ImageNet

dgs_vis_2:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v2_sim" ]
    combined_softmax: true

v2_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v2_embed_gen" ]

v2_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_ain_x1_0"
    weights: "./weights/osnet_ain_x1_0_imagenet.pth"
    nof_classes: 1000

# Visual - v3 - resnet50 from same-domain Re-ID

dgs_vis_3:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v3_sim" ]
    combined_softmax: true

v3_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v3_embed_gen"]

v3_embed_gen:
    module_name: "torchreid"
    model_name: "resnet50"
    weights: "pretrained"
    nof_classes: 1000

# Visual - v4 - resnet152 from same-domain Re-ID

dgs_vis_4:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v4_sim" ]
    combined_softmax: true

v4_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v4_embed_gen"]

v4_embed_gen:
    module_name: "torchreid"
    model_name: "resnet152"
    weights: "pretrained"
    nof_classes: 1000

