name: "Evaluate-IoU"
description: "Use the DGS tracker with a constant alpha module. 
With IoU as its only Similarity with an alpha value of 1."

device: "cuda"
print_prio: "INFO"
is_training: off
log_dir: "./results/own/eval/"

test:
    inactivity_threshold: 15
    max_track_length: 1
    save_images: off

# #### #
# DATA #
# #### #

dl_rcnn:
    module_name: "KeypointRCNNImageBackbone"
    dataset_path: "./data/"
    base_path: "./data/PoseTrack21/images/val/"
    batch_size: 8
    threshold: 0.75
    return_lists: true
    crop_size: !!python/tuple [256, 192]
    crop_mode: "zero-pad"
    # data_path:  # will be set in python script

dl_gt:
    module_name: "PoseTrack21_Image"
    dataset_path: "./data/PoseTrack21/"
    crops_folder: "./data/PoseTrack21/crops/256x192/val/"
    base_path: "./data/PoseTrack21/posetrack_data/val/"
    batch_size: 8
    return_lists: true
    # data_path: # will be set in python script

# ####### #
# MODULES #
# ####### #

combine_sim:
    module_name: "constant_alpha"
    alpha: [1.0]

vis_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_x1_0"
    weights: "pretrained"
    nof_classes: 5474  # PT21

# BOX - IoU

dgs_box:
    module_name: "DGS"
    combine: "combine_sim"
    names: ["box_sim"]
    combined_softmax: true

box_sim:
    module_name: "iou"

# Pose - OKS

dgs_pose:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "pose_sim" ]
    combined_softmax: true

pose_sim:
    module_name: "oks"
    format: "coco"


# Visual - v1

dgs_vis_1:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v1_sim" ]
    combined_softmax: true

v1_sim:
    module_name: "torchreid"
    metric: "CosineSimilarityMetric"
    embedding_generator_path: ["vis_embed_gen"]

# Visual - v2

dgs_vis_2:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v2_sim" ]
    combined_softmax: true

v2_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["vis_embed_gen" ]

# Visual - v3

dgs_vis_3:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v3_sim" ]
    combined_softmax: true

v3_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanSqDist"
    embedding_generator_path: ["vis_embed_gen"]

