name: "Evaluate-Single"
description: "Use the DGS tracker with a constant alpha module. 
With IoU as its only Similarity with an alpha value of 1."

device: "cuda:0"
print_prio: "INFO"
is_training: off
log_dir: "./results/own/eval/"
log_dir_add_date: false

test:
    inactivity_threshold: 15
    max_track_length: 1
    save_images: off
    # submission:  # will be set in python script

# #### #
# DATA #
# #### #

dgs_pt21_rcnn_256x192:
    module_name: "PoseTrack21_Image"
    dataset_path: "./data/PoseTrack21/"
    # crops_folder:  # will be set in python script
    # data_path:  # will be set in python script
    # base_path:  # will be set in python script

    batch_size: 8
    return_lists: true

    crop_size: !!python/tuple [256, 192]
    crop_mode: "zero-pad"

dgs_pt21_rcnn_256x128:
    module_name: "PoseTrack21_Image"
    dataset_path: "./data/PoseTrack21/"
    # crops_folder:  # will be set in python script
    # data_path:  # will be set in python script
    # base_path:  # will be set in python script

    batch_size: 8
    return_lists: true

    crop_size: !!python/tuple [256, 128]
    crop_mode: "zero-pad"

dgs_pt21_gt_256x192:
    module_name: "PoseTrack21_Image"
    dataset_path: "./data/PoseTrack21/"
    crops_folder: "./data/PoseTrack21/crops/256x192/val/"
    base_path: "./data/PoseTrack21/posetrack_data/val/"
    # data_path: # will be set in python script

    batch_size: 8
    return_lists: true

    crop_size: !!python/tuple [256, 192]
    crop_mode: "zero-pad"

dgs_pt21_gt_256x128:
    module_name: "PoseTrack21_Image"
    dataset_path: "./data/PoseTrack21/"
    crops_folder: "./data/PoseTrack21/crops/256x128/val/"
    base_path: "./data/PoseTrack21/posetrack_data/val/"
    # data_path: # will be set in python script

    batch_size: 8
    return_lists: true

    crop_size: !!python/tuple [256, 128]
    crop_mode: "zero-pad"

dgs_Dance_gt:
    module_name: "MOTImage"
    dataset_path: "./data/DanceTrack/"
    base_path: "./data/DanceTrack/val/**/gt/gt.txt"
    # data_path: # will be set in python script

    batch_size: 4
    return_lists: true

    crop_size: !!python/tuple [256, 192]
    crop_mode: "zero-pad"

    crop_key: "Crops"

dgs_Dance_rcnn_256x192:
    module_name: "MOTImage"
    dataset_path: "./data/DanceTrack/"
    base_path: "./data/DanceTrack/val/**/det/"
    # data_path: # will be set in python script

    batch_size: 4
    return_lists: true

    crop_size: !!python/tuple [256, 192]
    crop_mode: "zero-pad"

    # crop_key:  # will be set in python script

submission_pt21:
    module_name: "PoseTrack21"
    # file: # will be set in python script

submission_MOT:
    module_name: "MOT"
    # file: # will be set in python script

# ####### #
# MODULES #
# ####### #

combine_sim:
    module_name: "constant_alpha"
    alpha: [1.0]

# BOX - IoU

iou:
    module_name: "DGS"
    combine: "combine_sim"
    names: ["box_sim"]
    combined_softmax: true

box_sim:
    module_name: "iou"

# Pose - OKS

oks:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "pose_sim" ]
    combined_softmax: true

pose_sim:
    module_name: "oks"
    format: "coco"


# Visual - v1 - OSNet_x1_0 pretrained on ImageNet

OSNet:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v1_sim" ]
    combined_softmax: true

v1_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v1_embed_gen"]

v1_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_x1_0"
    weights: "./weights/osnet_x1_0_imagenet.pth"
    nof_classes: 1000


# Visual - v2 - OSNet_ain_x1_0 pretrained on ImageNet

OSNetAIN:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v2_sim" ]
    combined_softmax: true

v2_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v2_embed_gen" ]

v2_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_ain_x1_0"
    weights: "./weights/osnet_ain_x1_0_imagenet.pth"
    nof_classes: 1000

# Visual - v3 - resnet50 from same-domain Re-ID

Resnet50:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v3_sim" ]
    combined_softmax: true

v3_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v3_embed_gen"]

v3_embed_gen:
    module_name: "torchreid"
    model_name: "resnet50"
    weights: "pretrained"
    nof_classes: 1000

# Visual - v4 - resnet152 from same-domain Re-ID

Resnet152:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v4_sim" ]
    combined_softmax: true

v4_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v4_embed_gen"]

v4_embed_gen:
    module_name: "torchreid"
    model_name: "resnet152"
    weights: "pretrained"
    nof_classes: 1000

# Visual - v5 - OSNetAIN from cross domain ReID Duke-> Market

OSNetAIN_CrossDomainDuke:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v5_sim" ]
    combined_softmax: true

v5_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v5_embed_gen"]

v5_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_ain_x1_0"
    weights: "./weights/osnet_ain_x1_0_dukemtmcreid_256x128_amsgrad_ep90_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth"
    nof_classes: 1000

# Visual - v6 - OSNetIBN from cross domain ReID Duke-> Market

OSNetIBN_CrossDomainDuke:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v6_sim" ]
    combined_softmax: true

v6_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v6_embed_gen"]

v6_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_ibn_x1_0"
    weights: "./weights/osnet_ibn_x1_0_duke_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip.pth"
    nof_classes: 1000

# Visual - v7 - OSNetIBN from cross domain ReID Duke-> Market

OSNetAIN_CrossDomainMSMT17:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v7_sim" ]
    combined_softmax: true

v7_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v7_embed_gen"]

v7_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_ain_x1_0"
    weights: "./weights/osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth"
    nof_classes: 1000
