name: "Evaluate-Track-Weight"
description: "Use the DGS tracker with a constant alpha module. 
Evaluate a single similarity with a weight of alpha = 1 but with different values for the initial track weight."

device: "cuda:0"
print_prio: "INFO"
is_training: off
log_dir: "./results/own/eval/"
log_dir_add_date: false

test:
    inactivity_threshold: 15
    max_track_length: 1
    save_images: off
    # submission:  # will be set in python script

# #### #
# DATA #
# #### #

dgs_pt21_rcnn_256x192_val:
    module_name: "PoseTrack21_Image"
    dataset_path: "./data/PoseTrack21/"
    # crops_folder:  # will be set in python script
    # data_path:  # will be set in python script
    # base_path:  # will be set in python script

    batch_size: 8
    collate_fn: "lists"

    crop_size: !!python/tuple [256, 192]
    crop_mode: "zero-pad"

dgs_Dance_rcnn_256x192_val:
    module_name: "MOTImage"
    dataset_path: "./data/DanceTrack/"
    base_path: "./data/DanceTrack/val/**/det/"
    # data_path: # will be set in python script

    batch_size: 1
    collate_fn: "lists"

    crop_size: !!python/tuple [256, 192]
    crop_mode: "zero-pad"

    # crop_key:  # will be set in python script


# ########## #
# SUBMISSION #
# ########## #

submission_pt21:
    module_name: "PoseTrack21"
    # file: # will be set in python script

submission_MOT:
    module_name: "MOT"
    # file: # will be set in python script


# ################## #
# DGS and SIMILARITY #
# ################## #

combine_sim:
    module_name: "constant_alpha"
    alpha: [1.0]

# BOX - IoU

iou:
    module_name: "DGS"
    combine: "combine_sim"
    names: ["box_sim"]
    # new_track_weight:  # will be set by python script

box_sim:
    module_name: "iou"

# Pose - OKS

oks:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "pose_sim" ]
    # new_track_weight:  # will be set by python script

pose_sim:
    module_name: "oks"
    format: "coco"
    
# Visual - v1 - OSNet_x1_0 pretrained on ImageNet

OSNet:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "v1_sim" ]

v1_sim:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["v1_embed_gen"]

v1_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_x1_0"
    weights: "./weights/osnet_x1_0_imagenet.pth"
    nof_classes: 1000
