name: "Evaluate the DGS-Tracker"
description: "Evaluate the dynamically gated similarities tracker.
The tracker consists of three basic similarity modules.
Similarity by computing the bbox intersection over union, the key-point similarity using OKS, 
and the visual similarity using the OSNet Model from the torchreid package."

device: "cuda"
print_prio: "DEBUG"
is_training: off
log_dir: "./results/own/dgs/"

test:
    inactivity_threshold: 30
    save_images: on
    show_keypoints: off
    show_skeleton: off

engine:
    module_name: "DGSEngine"

# #### #
# DATA #
# #### #

dataloader_test:
    module_name: "PoseTrack21_Image"
    dataset_path: "./data/PoseTrack21/"
    data_path: "./posetrack_data/val/"
#    data_path: "./posetrack_data/val/014102_mpii_test.json"
    force_img_reshape: false
    crops_folder: "./crops/val/"
    batch_size: 1  # fixme

# ####### #
# MODULES #
# ####### #

dgs:
    module_name: "DGS"
    combine: "combine_similarities"
    names: ["visual_similarity", "pose_similarity", "box_similarity"]

combine_similarities:
    module_name: "constant_alpha"
    alpha: [0.5, 0.25, 0.25]

visual_similarity:
    module_name: "torchreid"
    model_name: "osnet_x1_0"
    similarity: "NegSoftmaxEuclideanDist"
    weights: "pretrained"
    nof_classes: 5474

pose_similarity:
    module_name: "oks"
    format: "coco"

box_similarity:
    module_name: "iou"
