name: "Evaluate-Pairwise-Combinations"
description: "Use the DGS tracker with a constant alpha module and a combination of two modules.
A python script will change the alpha values of the modules in 10% increments from 10 to 90 respectively."

device: "cuda:0"
print_prio: "INFO"
is_training: off
log_dir: "./results/own/eval/"
log_dir_add_date: false

test:
    inactivity_threshold: 15
    max_track_length: 1
    save_images: off
    submission: ["submission"]

# #### #
# DATA #
# #### #

dgs_pt21_rcnn_256x192_val:
    module_name: "PoseTrack21_Image"
    dataset_path: "./data/PoseTrack21/"
    # crops_folder:  # will be set in python script
    # base_path:  # will be set in python script
    # data_path:  # will be set in python script
    
    batch_size: 8
    collate_fn: "lists"

    crop_size: !!python/tuple [256, 192]
    crop_mode: "zero-pad"

dgs_pt21_gt_256x192_val:
    module_name: "PoseTrack21_Image"
    dataset_path: "./data/PoseTrack21/"
    crops_folder: "./data/PoseTrack21/crops/256x192/val/"
    base_path: "./data/PoseTrack21/posetrack_data/val/"
    # data_path: # will be set in python script

    batch_size: 8
    collate_fn: "lists"

    crop_size: !!python/tuple [256, 192]
    crop_mode: "zero-pad"

submission:
    module_name: "PoseTrack21"
    # file: # will be set in python script

# ################################ #
# SIMILARITY AND EMBED_GEN MODULES #
# ################################ #

combine_sim:
    module_name: "constant_alpha"
    # alpha: # will be set by python script

box_sim:
    module_name: "iou"

pose_sim:
    module_name: "oks"
    format: "coco"

visual_sim_OSNet:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["visual_embed_gen_OSNet"]

visual_embed_gen_OSNet:
    module_name: "torchreid"
    model_name: "osnet_x1_0"
    weights: "./weights/osnet_x1_0_imagenet.pth"
    nof_classes: 1000

visual_sim_OSNetAIN:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["visual_embed_gen_OSNetAIN"]

visual_embed_gen_OSNetAIN:
    module_name: "torchreid"
    model_name: "osnet_ain_x1_0"
    weights: "./weights/osnet_ain_x1_0_imagenet.pth"
    nof_classes: 1000

visual_sim_Resnet50:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["visual_embed_gen_Resnet50"]

visual_embed_gen_Resnet50:
    module_name: "torchreid"
    model_name: "resnet50"
    weights: "pretrained"
    nof_classes: 1000

visual_sim_Resnet152:
    module_name: "torchreid"
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["visual_embed_gen_Resnet152"]

visual_embed_gen_Resnet152:
    module_name: "torchreid"
    model_name: "resnet152"
    weights: "pretrained"
    nof_classes: 1000


# ########### #
# DGS MODULES #
# ########### #

# Combination 1 - IoU and OKS

iou_oks:
    module_name: "DGS"
    combine: "combine_sim"
    names: ["box_sim", "pose_sim"]
    similarity_softmax: true
    combined_softmax: true

# Combination 2 - IoU and Visual - OSNet

iou_OSNet:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "box_sim", "visual_sim_OSNet" ]
    similarity_softmax: true
    combined_softmax: true

# Combination 3 - OKS and Visual - OSNet

oks_OSNet:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "pose_sim", "visual_sim_OSNet" ]
    similarity_softmax: true
    combined_softmax: true

# Combination 4 - IoU and Visual - OSNetAIN

iou_OSNetAIN:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "box_sim", "visual_sim_OSNetAIN" ]
    similarity_softmax: true
    combined_softmax: true

# Combination 5 - OKS and Visual - OSNetAIN

oks_OSNetAIN:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "pose_sim", "visual_sim_OSNetAIN" ]
    similarity_softmax: true
    combined_softmax: true

# Combination 6 - IoU and Visual - Resnet50

iou_Resnet50:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "box_sim", "visual_sim_Resnet50" ]
    similarity_softmax: true
    combined_softmax: true

# Combination 7 - OKS and Visual - Resnet50

oks_Resnet50:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "pose_sim", "visual_sim_Resnet50" ]
    similarity_softmax: true
    combined_softmax: true

# Combination 8 - IoU and Visual - Resnet152

iou_Resnet152:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "box_sim", "visual_sim_Resnet152" ]
    similarity_softmax: true
    combined_softmax: true

# Combination 9 - OKS and Visual - Resnet152

oks_Resnet152:
    module_name: "DGS"
    combine: "combine_sim"
    names: [ "pose_sim", "visual_sim_Resnet152" ]
    similarity_softmax: true
    combined_softmax: true
