name: "Predict-Images"
description: "Use the trained DGS tracker to track and predict given a directory of images as input."

device: "cuda"
print_prio: "DEBUG"
is_training: off
log_dir: "./results/own/predict_trained/images/"

test:
    # submission:  # will be set in python script
    inactivity_threshold: 15
    max_track_length: 1
    save_images: on
    show_keypoints: on
    show_skeleton: on
    draw_kwargs:
        bbox_font_size: 90
        bbox_width: 8
        kp_width: 6

engine:
    module_name: "DGSEngine"
    model_type: "dgs"
    model_path: ["dgs"]

# ########## #
# SUBMISSION #
# ########## #

submission_pt21:
    module_name: "PoseTrack21"
    file: "./results/own/predict_trained/results/"

submission_MOT:
    module_name: "MOT"
    file: "./results/own/predict_trained/results/"

# #### #
# DATA #
# #### #

dataloader_dance:
    module_name: "KeypointRCNNImageBackbone"
    dataset_path: "./data/DanceTrack/"
    data_path: "./test/dancetrack0017/img1/"
    batch_size: 1
    
    score_threshold: 0.75
    iou_threshold: 0.35
    
    collate_fn: "lists"
    crop_size: !!python/tuple [ 256, 192 ]
    crop_mode: "zero-pad"
    load_img_crops: true  # will be set to true for visual similarity

dataloader_pt21:
    module_name: "KeypointRCNNImageBackbone"
    dataset_path: "./data/PoseTrack21/"
    data_path: "./data/PoseTrack21/images/val/012968_mpii_test/"
    batch_size: 1
    
    score_threshold: 0.85
    iou_threshold: 0.40
    
    collate_fn: "lists"
    crop_size: !!python/tuple [ 256, 192 ]
    crop_mode: "zero-pad"
    load_img_crops: true  # will be set to true for visual similarity


# ####### #
# MODULES #
# ####### #

dgs:
    module_name: "DGS"
    combine: "dynamic_alpha_combine"
    names: ["box_xywh_sim", "pose_sim_coco", "OSNet_sim"]

dynamic_alpha_combine:
    module_name: "dynamic_alpha"
    softmax: true
    # alpha_modules:  # will be set in python script


# ################## #
# SIMILARITY MODULES #
# ################## #

# BOX - IoU

box_xywh_sim:
    module_name: "iou"
    softmax: false
    train_key: "bbox_relative"

# Pose - OKS - COCO

pose_sim_coco:
    module_name: "oks"
    softmax: false
    train_key: "keypoints_relative"

    format: "coco"

# Visual - v1 - OSNet_x1_0 pretrained on ImageNet

OSNet_sim:
    module_name: "torchreid"
    softmax: false

    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["OSNet_embed_gen"]

OSNet_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_x1_0"
    weights: "./weights/osnet_x1_0_imagenet.pth"
    nof_classes: 1000
    is_training: off


# Visual - v2 - OSNet_ain_x1_0 pretrained on ImageNet

OSNetAIN_sim:
    module_name: "torchreid"
    softmax: false
    
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["OSNetAIN_embed_gen" ]

OSNetAIN_embed_gen:
    module_name: "torchreid"
    model_name: "osnet_ain_x1_0"
    weights: "./weights/osnet_ain_x1_0_imagenet.pth"
    nof_classes: 1000
    is_training: off

# Visual - v3 - resnet50 from same-domain Re-ID

Resnet50_sim:
    module_name: "torchreid"
    softmax: false
    
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["Resnet50_embed_gen"]

Resnet50_embed_gen:
    module_name: "torchreid"
    model_name: "resnet50"
    weights: "pretrained"
    nof_classes: 1000
    is_training: off

# Visual - v4 - resnet152 from same-domain Re-ID

Resnet152_sim:
    module_name: "torchreid"
    softmax: false
    
    metric: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["Resnet152_embed_gen"]

Resnet152_embed_gen:
    module_name: "torchreid"
    model_name: "resnet152"
    weights: "pretrained"
    nof_classes: 1000
    is_training: off

# ############# #
# ALPHA MODULES #
# ############# #

box_fc1_Sigmoid:
    module_name: "FullyConnectedAlpha"
    name: "bbox"
    hidden_layers: [4, 1]
    bias: true
    act_func: "Sigmoid"
    weight: "./weights/trained_alpha/Dance/box_xywh_sim/box_fc1_Sigmoid/ep004_lr0_0000100000.pth"

box_fc1_Tanh:
    module_name: "FullyConnectedAlpha"
    name: "bbox"
    hidden_layers: [4, 1]
    bias: true
    act_func: "Tanh"
    weight: "./weights/trained_alpha/Dance/box_xywh_sim/box_fc1_Tanh/ep004_lr0_0000100000.pth"


box_fc1_ReLU:
    module_name: "FullyConnectedAlpha"
    name: "bbox"
    hidden_layers: [4, 1]
    bias: true
    act_func: "ReLU"
    weight: "./weights/trained_alpha/Dance/box_xywh_sim/box_fc1_ReLU/ep004_lr0_0000100000.pth"


box_fc2_ReLUSigmoid:
    module_name: "FullyConnectedAlpha"
    name: "bbox"
    hidden_layers: [4, 8, 1]
    bias: true
    act_func: ["ReLU", "Sigmoid"]
    weight: "./weights/trained_alpha/Dance/box_xywh_sim/box_fc2_ReLUSigmoid/ep004_lr0_0000100000.pth"

box_fc2_2ReLU:
    module_name: "FullyConnectedAlpha"
    name: "bbox"
    hidden_layers: [4, 8, 1]
    bias: true
    act_func: "ReLU"
    weight: "./weights/trained_alpha/Dance/box_xywh_sim/box_fc2_2ReLU/ep004_lr0_0000100000.pth"


box_fc2_2Sigmoid:
    module_name: "FullyConnectedAlpha"
    name: "bbox"
    hidden_layers: [4, 8, 1]
    bias: true
    act_func: "Sigmoid"
    weight: "./weights/trained_alpha/Dance/box_xywh_sim/box_fc2_2Sigmoid/ep004_lr0_0000100000.pth"

    
# pose - COCO
pose_coco_fc1_Sigmoid:
    module_name: "SequentialCombinedAlpha"
    name: "keypoints"
    paths: ["Flatten", ["pose_coco_fc1_Sigmoid", "fc"]]
    fc:
        module_name: "FullyConnectedAlpha"
        hidden_layers: [ 34, 1 ]
        bias: true
        act_func: "Sigmoid"
    weight: "./weights/trained_alpha/pt21/pose_sim_coco/pose_coco_fc1_Sigmoid/ep004_lr0_0000100000.pth"

pose_coco_fc2_ReLUSigmoid:
    module_name: "SequentialCombinedAlpha"
    name: "keypoints"
    paths: ["Flatten", ["pose_coco_fc2_ReLUSigmoid", "fc"]]
    fc:
        module_name: "FullyConnectedAlpha"
        hidden_layers: [ 34, 8, 1 ]
        bias: true
        act_func: ["ReLU", "Sigmoid"]
    weight: "./weights/trained_alpha/pt21/pose_sim_coco/pose_coco_fc2_ReLUSigmoid/ep004_lr0_0000100000.pth"

pose_coco_fc2_2Sigmoid:
    module_name: "SequentialCombinedAlpha"
    name: "keypoints"
    paths: ["Flatten", ["pose_coco_fc2_2Sigmoid", "fc"]]
    fc:
        module_name: "FullyConnectedAlpha"
        hidden_layers: [ 34, 8, 1 ]
        bias: true
        act_func: "Sigmoid"
    weight: "./weights/trained_alpha/pt21/pose_sim_coco/pose_coco_fc2_2Sigmoid/ep004_lr0_0000100000.pth"


pose_coco_conv1o15k2fc1_Sigmoid:
    module_name: "SequentialCombinedAlpha"
    name: "keypoints"
    paths:
        - Conv1d:
            in_channels: 17
            out_channels: 15
            kernel_size: 2
            groups: 1
            bias: True
        - "Flatten"
        - [ "pose_coco_conv1o15k2fc1_Sigmoid", "fc" ]
    fc:
        module_name: "FullyConnectedAlpha"
        hidden_layers: [ 15, 1 ]
        bias: true
        act_func: "Sigmoid"
    weight: "./weights/trained_alpha/pt21/pose_sim_coco/pose_coco_conv1o15k2fc1_Sigmoid/ep004_lr0_0000100000.pth"

pose_coco_conv1o15k2fc2_ReLUSigmoid:
    module_name: "SequentialCombinedAlpha"
    name: "keypoints"
    paths:
        - Conv1d:
            in_channels: 17
            out_channels: 15
            kernel_size: 2
            groups: 1
            bias: True
        - "Flatten"
        - [ "pose_coco_conv1o15k2fc2_ReLUSigmoid", "fc" ]
    fc:
        module_name: "FullyConnectedAlpha"
        hidden_layers: [ 15, 8, 1 ]
        bias: true
        act_func: ["ReLU", "Sigmoid"]
    weight: "./weights/trained_alpha/pt21/pose_sim_coco/pose_coco_conv1o15k2fc2_ReLUSigmoid/ep004_lr0_0000100000.pth"

pose_coco_conv1o15k2fc2_2Sigmoid:
    module_name: "SequentialCombinedAlpha"
    name: "keypoints"
    paths:
        - Conv1d:
            in_channels: 17
            out_channels: 15
            kernel_size: 2
            groups: 1
            bias: True
        - "Flatten"
        - [ "pose_coco_conv1o15k2fc2_2Sigmoid", "fc" ]
    fc:
        module_name: "FullyConnectedAlpha"
        hidden_layers: [ 15, 8, 1 ]
        bias: true
        act_func: "Sigmoid"
    weight: "./weights/trained_alpha/pt21/pose_sim_coco/pose_coco_conv1o15k2fc2_2Sigmoid/ep004_lr0_0000100000.pth"

# visual - OSNet
visual_osn_fc1_Sigmoid:
  module_name: "FullyConnectedAlpha"
  name: "embedding"
  hidden_layers: [512, 1]
  bias: true
  act_func: "Sigmoid"
  weight: "./weights/trained_alpha/Dance/OSNet_sim/visual_osn_fc1_Sigmoid/ep004_lr0_0000100000.pth"

visual_osn_fc3_2ReLUSigmoid:
  module_name: "FullyConnectedAlpha"
  name: "embedding"
  hidden_layers: [512, 256, 128, 1]
  bias: true
  act_func: ["ReLU", "ReLU", "Sigmoid"]
  weight: "./weights/trained_alpha/Dance/OSNet_sim/visual_osn_fc3_2ReLUSigmoid/ep004_lr0_0000100000.pth"

visual_osn_fc3_3Sigmoid:
  module_name: "FullyConnectedAlpha"
  name: "embedding"
  hidden_layers: [512, 256, 128, 1]
  bias: true
  act_func: "Sigmoid"
  weight: "./weights/trained_alpha/Dance/OSNet_sim/visual_osn_fc3_3Sigmoid/ep004_lr0_0000100000.pth"

visual_osn_fc5_5Sigmoid:
  module_name: "FullyConnectedAlpha"
  name: "embedding"
  hidden_layers: [512, 256, 128, 64, 32, 1]
  bias: true
  act_func: "Sigmoid"
  weight: "./weights/trained_alpha/Dance/OSNet_sim/visual_osn_fc5_5Sigmoid/ep004_lr0_0000100000.pth"

visual_osn_fc5_4ReLUSigmoid:
  module_name: "FullyConnectedAlpha"
  name: "embedding"
  hidden_layers: [512, 256, 128, 64, 32, 1]
  bias: true
  act_func: ["ReLU", "ReLU", "ReLU", "ReLU", "Sigmoid"]
  weight: "./weights/trained_alpha/Dance/OSNet_sim/visual_osn_fc5_4ReLUSigmoid/ep004_lr0_0000100000.pth"

# visual - Resnet
visual_res_fc1_Sigmoid:
  module_name: "FullyConnectedAlpha"
  name: "embedding"
  hidden_layers: [2048, 1]
  bias: true
  act_func: "Sigmoid"
  weight: "./weights/trained_alpha/Dance/Resnet50_sim/visual_res_fc1_Sigmoid/ep004_lr0_0000100000.pth"

visual_res_fc3_3Sigmoid:
  module_name: "FullyConnectedAlpha"
  name: "embedding"
  hidden_layers: [2048, 512, 64, 1]
  bias: true
  act_func: "Sigmoid"
  weight: "./weights/trained_alpha/Dance/Resnet50_sim/visual_res_fc3_3Sigmoid/ep004_lr0_0000100000.pth"

visual_res_fc3_2ReLUSigmoid:
  module_name: "FullyConnectedAlpha"
  name: "embedding"
  hidden_layers: [2048, 512, 64, 1]
  bias: true
  act_func: ["ReLU", "ReLU", "Sigmoid"]
  weight: "./weights/trained_alpha/Dance/Resnet50_sim/visual_res_fc3_2ReLUSigmoid/ep004_lr0_0000100000.pth"

visual_res_fc5_5Sigmoid:
  module_name: "FullyConnectedAlpha"
  name: "embedding"
  hidden_layers: [2048, 1024, 256, 128, 64, 1]
  bias: true
  act_func: "Sigmoid"
  weight: "./weights/trained_alpha/Dance/Resnet50_sim/visual_res_fc5_5Sigmoid/ep004_lr0_0000100000.pth"

visual_res_fc5_4ReLUSigmoid:
  module_name: "FullyConnectedAlpha"
  name: "embedding"
  hidden_layers: [2048, 1024, 256, 128, 64, 1]
  bias: true
  act_func: ["ReLU", "ReLU", "ReLU", "ReLU", "Sigmoid"]
  weight: "./weights/trained_alpha/Dance/Resnet50_sim/visual_res_fc5_4ReLUSigmoid/ep004_lr0_0000100000.pth"
