name: DGS
channels:
  - defaults
  - "nvidia/label/cuda-11.8.0"
dependencies:
  - python==3.10.*
  - pip
  - cuda-toolkit  # conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit
  - pytorch::torchvision=0.16.*
  - pytorch::torchaudio=2.1.*
  - pytorch::pytorch-cuda=11.8
  - pytorch::pytorch=2.1.*
  - anaconda::cython=3.0.*
  - anaconda::natsort
  - anaconda::numpy
  - anaconda::scipy
  - conda-forge::jinja2
  - conda-forge::munkres
  - conda-forge::ninja
  - conda-forge::easydict
  - conda-forge::pycocotools=2.0.*
  - conda-forge::pyyaml=6.0.*
  - conda-forge::terminaltables
  - conda-forge::tensorboardx
  - conda-forge::typeguard
  - conda-forge::tqdm
  - conda-forge::visdom
  #  - conda-forge::pytorch3d
  #  - conda-forge::fvcore
  - pip:
      # Additional Packages for DGS
      - pylint
      # Set up halpecocotools
      - -e ./dependencies/halpecocotools/PythonAPI
      # Torchreid - install requirements and Set up torchreid and cythonize
      # somehow installing requirements does not work just by calling setup,
      # can't find cv2 even with it in the requirements
      - -r ./dependencies/torchreid/requirements.txt
      - -e ./dependencies/torchreid
      # Requirements for Alpha Pose
      - -e ./dependencies/AlphaPose_Fork
