name: "WIP - Train Pose-Embeddings"
description: "Train the embeddings for a pose-based embedding generator 
    using the embedding generators of the dgs module."

device: "cuda"
print_prio: "INFO"
is_training: on

train:
    batch_size: 32
    epochs: 1
    loss: "TorchreidCrossEntropyLoss"
    loss_kwargs:
        num_classes: 5474
    optimizer: "Adam"

test:
    batch_size: 128
    metric: "CosineDistance"

# #### #
# DATA #
# #### #

# FIXME: Set flag to not load image data

dataloader_train:
    module_name: "PoseTrack21"
    dataset_path: "./data/PoseTrack21/"
    data_path: "./posetrack_person_search/train.json"
    batch_size: 2048
    id_map: "./weights/pt21_id_map.json"

dataloader_gallery:
    module_name: "PoseTrack21"
    dataset_path: "./data/PoseTrack21/"
    data_path: "./posetrack_person_search/val.json"
    batch_size: 2048

dataloader_query:
    module_name: "PoseTrack21"
    dataset_path: "./data/PoseTrack21/"
    data_path: "./posetrack_person_search/query.json"
    batch_size: 2048

# ####### #
# MODULES #
# ####### #

pose_embedding_generator:
    module_name: "LinearPBEG"  # see `dgs.models.embedding_generator`
    embedding_size: 16
    hidden_layers: []
    joint_shape: (17, 2)  # (J, kp_dim)
    bbox_format: "XYWH"
    bias: True
#    only applicable for module "KeyPointConvolutionPBEG"
#    hidden_layers_kp: None
#    nof_kernels: 5

