name: "Predict-Images"
description: "Use the DGS tracker to track and predict given a directory of images as input."

device: "cuda"
print_prio: "DEBUG"
is_training: off
log_dir: "./results/own/dgs_predict/rcnn_images/"

test:
    inactivity_threshold: 15
    max_track_length: 1
    save_images: on
    show_keypoints: on
    show_skeleton: on
    draw_kwargs:
        bbox_font_size: 90
        bbox_width: 8

# #### #
# DATA #
# #### #

dataloader_test:
    module_name: "ImageRCNN"
    dataset_path: "./data/"
    path: "./test/"
    batch_size: 1  # fixme
    threshold: 0.75

# ####### #
# MODULES #
# ####### #

dgs:
    module_name: "DGS"
    combine: "combine_similarities"
    names: ["visual_similarity", "pose_similarity", "box_similarity"]

combine_similarities:
    module_name: "constant_alpha"
    alpha: [0.5, 0.25, 0.25]

visual_similarity:
    module_name: "torchreid"
    similarity: "NegSoftmaxEuclideanDist"
    embedding_generator_path: ["visual_similarity", "vis_emb_gen"]
    vis_emb_gen:
        module_name: "torchreid"
        nof_classes: 1000
        weights: "pretrained"
        model_name: "osnet_x1_0"

pose_similarity:
    module_name: "oks"
    format: "coco"

box_similarity:
    module_name: "iou"
