name: "The most simple DGS tracker"
description: "Use the most basic module for every step."

device: "cuda"
print_prio: "normal"
training: off

# Modules

dataset:
    module_name: "PoseTrack21"

embedding_generator_visual:
    module_name: "torchreid"

embedding_generator_pose:
    module_name: "LinearPBEG"

pose_warping_module:
    module_name: "kalman"
