name: "The most simple DGS tracker"
description: "Use the most basic module for every step."

device: "cuda"
print_prio: "normal"
working_memory_size: 30
training: off

batch_size: 32

dataset:
    model: "PoseTrack21"

# Modules

backbone:
    model: "AlphaPose"

visual_embedding_generator:
    model: "torchreid"

visual_similarity:
    model: "dummy"

pose_embedding_generator:
    model: "dummy"

pose_warping_module:
    model: "kalman"

pose_similarity:
    model: "dummy"