name: "The most simple DGS tracker"
description: "Use the most basic module for every step."

device: "cuda"
is_training: off

# Modules

dataset:
    module_name: "PoseTrack21"

embedding_generator_visual:
    module_name: "TorchreidModel"

embedding_generator_pose:
    module_name: "LinearPBEG"
