name: "The most simple DGS tracker"
description: "Use the most basic module for every step."

device: "cuda"
print_prio: "normal"
training: off

batch_size: 8

# Modules

dataset:
    module_name: "PoseTrack21"

visual_embedding_generator:
    module_name: "torchreid"

pose_embedding_generator:
    module_name: "LinearPBEG"

pose_warping_module:
    module_name: "kalman"
