name: "Train Visual Embedding Generator"
description: "Train the visual embedding generator using torchreid models. 
The embedding generator can be used by the similarity modules. 
This config uses the engine of the dgs module."

device: "cuda"
print_prio: "DEBUG"
is_training: on
log_dir: "./results/own/visual_sim/"


train:
    epochs: 5
#    loss: "CrossEntropyLoss"
    loss: "TorchreidCrossEntropyLoss"
    loss_kwargs:
        num_classes: 5474
    optimizer: "Adam"
    optimizer_kwargs:
        lr: 0.0003
        weight_decay: 0.0005
        betas: [0.9, 0.99]
    nof_classes: 5474
    topk_acc: [1, 5]
    save_interval: 1
    scheduler: "StepLR"
    scheduler_kwargs:
        step_size: 1
        gamma: 0.1

test:
    metric: "EuclideanSquare"  # used to compute the distance matrix between target and predicted embeddings
    topk_cmc: [1,2,3,5,10,20,50]
    write_embeds: [False, False]

# #### #
# DATA #
# #### #

train_dl:
    module_name: "PoseTrack21"
    dataset_path: "./data/PoseTrack21/"
    json_path: "./posetrack_person_search/train.json"
    crops_folder: "./crops/train/"
    batch_size: 256
    id_map: "./weights/pt21_id_map.json"
    force_img_reshape: true

gallery_dl:
    module_name: "PoseTrack21"
    dataset_path: "./data/PoseTrack21/"
    json_path: "./posetrack_person_search/val.json"
    force_img_reshape: true
    crops_folder: "./crops/gallery/"
    batch_size: 256

query_dl:
    module_name: "PoseTrack21"
    dataset_path: "./data/PoseTrack21/"
    json_path: "./posetrack_person_search/query.json"
    force_img_reshape: true
    crops_folder: "./crops/query/"
    batch_size: 256

# ####### #
# MODULES #
# ####### #

engine:
    module_name: "VisualSimilarityEngine"

visual_similarity:
    module_name: "torchreid"  # see `dgs.models.similarity.__init__`
    model_name: "osnet_ain_x1_0"
    similarity: "EuclideanSquare"
    weights: "pretrained"
    embedding_size: 512
    nof_classes: 5474
