name: "Train Pose-Embeddings"
description: "Train the embeddings for a pose-based embedding generator using the dgs module."

device: "cuda"
print_prio: "normal"
is_training: on

train:
    batch_size: 32
    epochs: 1
    loss: "dummy"
    metric: "dummy"

test:
    batch_size: 128

# Modules

dataset:
    module_name: "PoseTrack21"

pose_embedding_generator:
    module_name: "LinearPBEG"  # see `dgs.models.embedding_generator`
    embedding_size: 16
    hidden_layers: []
    joint_shape: (17, 2)  # (J, kp_dim)
    bbox_format: "XYWH"
    bias: True
#    only applicable for module "KeyPointConvolutionPBEG"
#    hidden_layers_kp: None
#    nof_kernels: 5

