name: Run CI

on: [push, pull_request]

jobs:
  build:
    name: Run pylint and tests
    runs-on: ubuntu-latest
    #    strategy:
    #      fail-fast: false
    #      matrix:
    #        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: DGS
        environment-file: environment.yaml
        auto-update-conda: "true"
    - name: Analysing the code with pylint
      run: |
        pylint -j 0 .
    - name: Test using unittest
      run: |
        python -m unittest discover ./tests/ "test__*.py"
