name: Run CI

on: [ push, pull_request ]

jobs:
  build:
    name: Run pylint and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository including submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Setup pip, install dependencies with test and linting requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements_test.txt
          pip install --force-reinstall -e .

      - name: Analysing the code with black
        run: |
          black .

      - name: Analysing the code with pylint
        run: |
          pylint .

      - name: Test using unittest and run coverage
        run: |
          TQDM_DISABLE=1 coverage run -m unittest discover -s ./tests/ -p "test__*.py"

      - name: Generate Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          thresholds: '60 80'
          output: console

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md