name: Run CI

on: [ push, pull_request ]

jobs:
  build:
    name: Run pylint and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository including submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Setup pip, install dependencies with test and linting requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements_test.txt

      - name: Analysing the code with black
        run: |
          black .

      - name: Analysing the code with pylint
        run: |
          pylint .

      - name: Test using unittest and run coverage
        run: |
          coverage -m unittest discover ./tests/ "test__*.py"
