name: 'coverage'
on:
    pull_request
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            -   name: Get coverage for PR
                uses: orgoro/coverage@v3.1
                with:
                    coverageFile: coverage/coverage.xml
                    token: ${{ secrets.GITHUB_TOKEN }}