name: 'coverage'
on:
    pull_request

# Explicitely set permissions to allow Dependabot workflow runs to write in the PR for coverage's reporting.
# By default, these are read-only when the actions are ran by Dependabot
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
permissions:
    pull-requests: write

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            -   name: Get coverage for PR
                uses: orgoro/coverage@v3.2
                with:
                    coverageFile: coverage/coverage.xml
                    token: ${{ secrets.GITHUB_TOKEN }}