name: "Deploy Docs"
on: [ push, pull_request ]
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deployment
        id: deployment
        uses: sphinx-notes/pages@v3
        with:
          python_version: "3.10"
          requirements_path: "./docs/requirements_docs.txt"
          cache: false
          checkout: true
          publish: true
          sphinx_build_options: "-E -a"  # force rebuild
