name: "Deploy Docs"
on: [ push, pull_request ]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      -   name: Checkout git repository including submodules
          uses: actions/checkout@v4
          with:
            submodules: recursive
      - name: Linkcheck
        id: linkcheck
        uses: sphinx-notes/pages@v3
        with:
          python_version: "3.10"
          requirements_path: "./docs/requirements_docs.txt"
          cache: false
          checkout: false
          publish: false  # don't publish, does not build everything correctly
          sphinx_build_options: "-E -a --jobs auto -b linkcheck"  # force rebuild and use linkcheck builder
      - name: Deployment
        id: deployment
        uses: sphinx-notes/pages@v3
        with:
          python_version: "3.10"
          requirements_path: "./docs/requirements_docs.txt"
          cache: true  # cache here? Because linkcheck built already?
          checkout: false
          publish: true
          sphinx_build_options: "--jobs auto"  # linkcheck did rebuild, therefore, this doesn't need it?
