name: "Deploy docs to github-pages"
on: [ push, pull_request ]
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deployment
        id: deployment
        uses: sphinx-notes/pages@v3
        with:
          python_version: 3.10
          cache: true
          checkout: true
          publish: true
